### ISSUE TITLE
sorted_sam16s error

### ISSUE THREAD

**Issue by ajcardenasb** [songweizhi/MarkerMAG#1]
Hello,

Thanks you for developing MarkerMAG, the tool looks really promising! 

I'm having the following error every time I try to run MarkerMAG link. 

Traceback (most recent call last):
  File "/home/cardena/miniconda3/bin/MarkerMAG", line 126, in <module>
    link_16s.link_16s(args)
  File "/home/cardena/miniconda3/lib/python3.7/site-packages/MarkerMAG/link_16s.py", line 2703, in link_16s
    reads_vs_16s_sam                    = args['sorted_sam16s']
KeyError: 'sorted_sam16s'

The command I'm using is:

MarkerMAG link -p sponges_markerMAG_output -r1 sponge_R1.fasta -r2 sponge_R2.fasta -marker interesing_bacteria.fasta -mag ./binning/chosen_bins -x fa -t 64 -tmp -force

I tried with and without renaming fasta files using "MarkerMAG rename_reads" but I always get to the same error.  
Am I missing something?

Thanks for clarification!
Anny

**Comment by songweizhi** [comment]
Thanks for your interest in using MarkerMAG, Anny. This issue has been fixed in the latest version (v1.0.41).
Best,
Weizhi

**Comment by ajcardenasb** [comment]
Thank you, Weizhi! I'll try it out
