### ISSUE TITLE
barrnap_16S: 'No query genome detected'

### ISSUE THREAD

**Issue by Laura-Alex** [songweizhi/MarkerMAG#3]
Hello folks,

I'm pretty excited about MarkerMAG. Sadly, I can't seem to figure out the supplementary barrnap_16S module.

Standard barrnap works well on my setup. However, when I try to run barrnap 16S on MEGAHIT results as follows:

`MarkerMAG barrnap_16s -p ALW -g /scratch/username/megahit/sample/ALW/final.contigs.fa -x fa -t 6 -force`

Then I get the following error:
`No query genome detected, program exited!`

I have checked whether the file final.contigs.fa is in that location and contain stuff with `more` , and it does indeed seem to be there. I know I can run barrnap for now and just delete what I don't need, but it would be nice to see if there's anything I can do to use the simpler version.

**Comment by songweizhi** [comment]
Hi Laura, 
The barrnap_16s module doesn't support single file input in the current version, I'll include this feature in the next release. to run barrnap_16s on a single file, you can put that file in a folder and provide that folder to barrnap_16s with -g.
Cheers,
Weizhi

**Comment by Laura-Alex** [comment]
Much appreciated, Weizhi!
