### ISSUE TITLE
Add the possibility to use `.gz` files

### ISSUE THREAD

**Issue by AlessioMilanese** [songweizhi/MarkerMAG#4]
Hi,

I really like the tool interface!

Very often the reads file are gzipped (due to the big size of metagenomic samples), it would be great if you can add the possibility to provide directly `.gz` files as input for `-r1` and `-r2`.

**Comment by songweizhi** [comment]
Thanks for your suggestion, however, we currently have no plan in supporting the zipped input reads files, as in most cases, you may need to unzip and rename you reads to assure that the ids of reads in pair are in the format of XXXX.1 and XXXX.2 before MarkerMAG.
